export const countries = [
  { value: "tr", label: "Turkey", code: "TR", phoneCode: "+90" },
  { value: "us", label: "United States", code: "US", phoneCode: "+1" },
  { value: "gb", label: "United Kingdom", code: "GB", phoneCode: "+44" },
  { value: "de", label: "Germany", code: "DE", phoneCode: "+49" },
  { value: "fr", label: "France", code: "FR", phoneCode: "+33" },
  { value: "it", label: "Italy", code: "IT", phoneCode: "+39" },
  { value: "es", label: "Spain", code: "ES", phoneCode: "+34" },
  { value: "nl", label: "Netherlands", code: "NL", phoneCode: "+31" },
  { value: "be", label: "Belgium", code: "BE", phoneCode: "+32" },
  { value: "ch", label: "Switzerland", code: "CH", phoneCode: "+41" },
  { value: "at", label: "Austria", code: "AT", phoneCode: "+43" },
  { value: "pl", label: "Poland", code: "PL", phoneCode: "+48" },
  { value: "se", label: "Sweden", code: "SE", phoneCode: "+46" },
  { value: "no", label: "Norway", code: "NO", phoneCode: "+47" },
  { value: "dk", label: "Denmark", code: "DK", phoneCode: "+45" },
  { value: "fi", label: "Finland", code: "FI", phoneCode: "+358" },
  { value: "pt", label: "Portugal", code: "PT", phoneCode: "+351" },
  { value: "gr", label: "Greece", code: "GR", phoneCode: "+30" },
  { value: "ie", label: "Ireland", code: "IE", phoneCode: "+353" },
  { value: "ca", label: "Canada", code: "CA", phoneCode: "+1" },
  { value: "au", label: "Australia", code: "AU", phoneCode: "+61" },
  { value: "jp", label: "Japan", code: "JP", phoneCode: "+81" },
  { value: "kr", label: "South Korea", code: "KR", phoneCode: "+82" },
  { value: "sg", label: "Singapore", code: "SG", phoneCode: "+65" },
  { value: "nz", label: "New Zealand", code: "NZ", phoneCode: "+64" },
]
