export const countries = [
  { value: "tr", label: "Turkey", code: "TR", phoneCode: "+90" },
  { value: "us", label: "United States", code: "US", phoneCode: "+1" },
  { value: "gb", label: "United Kingdom", code: "GB", phoneCode: "+44" },
  { value: "de", label: "Germany", code: "DE", phoneCode: "+49" },
  { value: "fr", label: "France", code: "FR", phoneCode: "+33" },
  { value: "it", label: "Italy", code: "IT", phoneCode: "+39" },
  { value: "es", label: "Spain", code: "ES", phoneCode: "+34" },
  { value: "nl", label: "Netherlands", code: "NL", phoneCode: "+31" },
  { value: "be", label: "Belgium", code: "BE", phoneCode: "+32" },
  { value: "ch", label: "Switzerland", code: "CH", phoneCode: "+41" },
  { value: "at", label: "Austria", code: "AT", phoneCode: "+43" },
  { value: "pl", label: "Poland", code: "PL", phoneCode: "+48" },
  { value: "se", label: "Sweden", code: "SE", phoneCode: "+46" },
  { value: "no", label: "Norway", code: "NO", phoneCode: "+47" },
  { value: "dk", label: "Denmark", code: "DK", phoneCode: "+45" },
  { value: "fi", label: "Finland", code: "FI", phoneCode: "+358" },
  { value: "pt", label: "Portugal", code: "PT", phoneCode: "+351" },
  { value: "gr", label: "Greece", code: "GR", phoneCode: "+30" },
  { value: "ie", label: "Ireland", code: "IE", phoneCode: "+353" },
  { value: "ca", label: "Canada", code: "CA", phoneCode: "+1" },
  { value: "au", label: "Australia", code: "AU", phoneCode: "+61" },
  { value: "jp", label: "Japan", code: "JP", phoneCode: "+81" },
  { value: "kr", label: "South Korea", code: "KR", phoneCode: "+82" },
  { value: "sg", label: "Singapore", code: "SG", phoneCode: "+65" },
  { value: "nz", label: "New Zealand", code: "NZ", phoneCode: "+64" },
]

export const ships = [
  {
    id: "1",
    name: "MV Atlantic Pioneer",
    type: "Container Ship",
    imo: "9234567",
    flag: "Panama",
    status: "Active",
    location: "Port of Rotterdam",
    capacity: "18,000 TEU",
    captain: "Captain James Morrison",
    yearBuilt: 2019,
    lastInspection: "2024-01-15",
    nextMaintenance: "2024-03-20",
    image: "/cargo-ship.jpg"
  },
  {
    id: "2",
    name: "MV Mediterranean Star",
    type: "Bulk Carrier",
    imo: "9345678",
    flag: "Liberia",
    status: "In Transit",
    location: "Mediterranean Sea",
    capacity: "75,000 DWT",
    captain: "Captain Maria Rodriguez",
    yearBuilt: 2020,
    lastInspection: "2024-02-10",
    nextMaintenance: "2024-04-15",
    image: "/cargo-ship.jpg"
  },
  {
    id: "3",
    name: "MV Baltic Explorer",
    type: "Tanker",
    imo: "9456789",
    flag: "Marshall Islands",
    status: "Maintenance",
    location: "Hamburg Shipyard",
    capacity: "115,000 DWT",
    captain: "Captain Erik Hansen",
    yearBuilt: 2018,
    lastInspection: "2024-01-20",
    nextMaintenance: "2024-02-28",
    image: "/cargo-ship.jpg"
  },
  {
    id: "4",
    name: "MV Pacific Voyager",
    type: "Container Ship",
    imo: "9567890",
    flag: "Singapore",
    status: "Active",
    location: "Port of Singapore",
    capacity: "14,500 TEU",
    captain: "Captain Li Wei",
    yearBuilt: 2021,
    lastInspection: "2024-02-05",
    nextMaintenance: "2024-05-10",
    image: "/cargo-ship.jpg"
  },
  {
    id: "5",
    name: "MV Arctic Breaker",
    type: "Ice Breaker",
    imo: "9678901",
    flag: "Norway",
    status: "Active",
    location: "Arctic Ocean",
    capacity: "15,000 HP",
    captain: "Captain Olaf Andersen",
    yearBuilt: 2017,
    lastInspection: "2024-01-30",
    nextMaintenance: "2024-04-01",
    image: "/cargo-ship.jpg"
  },
  {
    id: "6",
    name: "MV Indian Ocean",
    type: "Bulk Carrier",
    imo: "9789012",
    flag: "India",
    status: "In Transit",
    location: "Indian Ocean",
    capacity: "82,000 DWT",
    captain: "Captain Raj Patel",
    yearBuilt: 2022,
    lastInspection: "2024-02-12",
    nextMaintenance: "2024-06-01",
    image: "/cargo-ship.jpg"
  }
]
